import time
import warnings
from functools import lru_cache
from pathlib import Path
from typing import Any

import verifiers as vf
from datasets import Dataset, load_dataset
from datasets.combine import concatenate_datasets

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=FutureWarning)
    from scicode_core.gen.models import extract_python_script
    from scicode_core.parse.parse import (
        extract_function_name,
        get_function_from_code,
    )

from verifiers.envs.sandbox_env import SandboxState
from verifiers.types import Messages, State
from verifiers.utils.logging_utils import print_time

warnings.filterwarnings("ignore", message="invalid escape sequence", category=SyntaxWarning)

# data directory containing prompt templates and ground truth code for skipped steps
DATA_DIR = Path(__file__).parent / "data"


@lru_cache(maxsize=None)
def load_data_file(filename: str) -> str:
    """Load a file from the data directory with caching."""
    return (DATA_DIR / filename).read_text(encoding="utf-8")


def get_prompt_template(with_background: bool) -> str:
    """Load prompt template from data files."""
    if with_background:
        return load_data_file("background_comment_template.txt")
    else:
        return load_data_file("multistep_template.txt")


def build_dataset(with_background: bool = True) -> Dataset:
    def process_example(x: dict) -> dict:
        return {
            "prompt": [],  # built dynamically in setup_state
            "answer": "",
            "info": {
                "problem_id": x["problem_id"],
                "dependencies": x["required_dependencies"],
                "num_steps": len(x["sub_steps"]),
                "steps": x["sub_steps"],
                "with_background": with_background,
            },
        }

    val_dataset = load_dataset("SciCode1/SciCode", split="validation").map(process_example)
    test_dataset = load_dataset("SciCode1/SciCode", split="test").map(process_example)

    # cast features to match before concatenating
    features = val_dataset.features
    test_dataset = test_dataset.cast(features)
    return concatenate_datasets([val_dataset, test_dataset])


def is_skip_step(step_number: str) -> bool:
    """Check if a step is skipped by looking for its ground truth file in the data directory.

    Skip steps have pre-provided ground truth code in data/{step_number}.txt files.
    This matches the official SciCode behavior where certain steps are not generated by the model.
    """
    return (DATA_DIR / f"{step_number}.txt").exists()


def get_skip_step_code(step_number: str) -> str:
    """Get ground truth code for a skipped step, or empty string if not a skipped step."""
    if not is_skip_step(step_number):
        return ""
    return load_data_file(f"{step_number}.txt")


def format_step_description(step: dict, code: str, with_background: bool) -> str:
    """Format a single step's description for inclusion in previous steps.

    Matches official SciCode format: description + background (if enabled) + code + separator.
    No python fences around code (matching official behavior).
    """
    parts = [step["step_description_prompt"]]
    if with_background and step["step_background"]:
        parts[0] = step["step_description_prompt"] + "\n" + step["step_background"]
    parts.append(code)
    parts.append("------")
    return "\n\n".join(parts)


def format_prompt(step: dict, dependencies: str, with_background: bool, previous_steps_description: str = "") -> str:
    """Formats the next step's prompt using official SciCode template format."""
    # Build next_step_str: description + background (if enabled) + function header + return line
    # This matches the official format where everything is combined without fences
    next_step_parts = [step["step_description_prompt"]]
    if with_background and step["step_background"]:
        next_step_parts.append(step["step_background"])
    next_step_parts.append(f"{step['function_header']}\n\n{step['return_line']}")
    next_step_str = "\n\n".join(next_step_parts)

    return get_prompt_template(with_background).format(
        problem_steps_str=previous_steps_description,
        next_step_str=next_step_str,
        dependencies=dependencies,
    )


class SciCodeParser(vf.Parser):
    """Extracts fenced Python code from completions."""

    def parse_answer(self, completion) -> str | None:
        # parse answer
        answer = super().parse_answer(completion)
        if not answer:
            return None

        # parse code (using scicode parsing logic)
        parsed_code = extract_python_script(answer)
        if not parsed_code:
            return None

        return parsed_code


class SciCodeMonitorRubric(vf.Rubric):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.add_metric(self.verification_time)
        self.add_metric(self.num_steps)

    async def num_steps(self, state: State) -> int:
        """Number of steps in the problem."""
        return int(state["info"]["num_steps"])

    async def verification_time(self, state: State) -> float:
        """Time taken to verify the problem."""
        return state.get("verification_time", 0.0)


class SciCodeRubric(vf.Rubric):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.add_reward_func(self.main_problem_score, 0.0)
        self.add_reward_func(self.subproblem_score, 1.0)

    def subproblem_score(self, state: State) -> float:
        """The fraction of subproblems solved."""
        return state.get("pass_rate", 0.0)

    def main_problem_score(self, state: State) -> float:
        """The main problem is solved if all steps are solved."""
        return 1.0 if state.get("pass_rate", 0) == 1.0 else 0.0


class SciCodeEnv(vf.SandboxEnv):
    DOCKER_IMAGE = "cmakj7hyo002rz091pdjngniy/scicode:latest"
    H5_FILE_PATH = "/data/test_data.h5"

    def __init__(
        self,
        sandbox_name: str = "scicode",
        timeout_per_test: int = 120,  # seconds
        **kwargs: Any,
    ):
        super().__init__(
            docker_image=self.DOCKER_IMAGE,
            sandbox_name=sandbox_name,
            timeout_per_command_seconds=timeout_per_test,
            memory_gb=4,
            disk_size_gb=5,
            max_turns=-1,
            parser=SciCodeParser(),
            rubric=SciCodeRubric(),
            **kwargs,
        )

        # remove bash tool from model's view - scicode is conversation-based, not tool-based
        # the bash method is still available internally via self.bash() for setup and tests
        self.remove_tool(self.bash)

        self.add_rubric(SciCodeMonitorRubric())
        self.timeout_per_test = timeout_per_test

    @vf.stop
    async def all_steps_completed(self, state: State) -> bool:
        """Stop when all problem steps have been completed."""
        return len(state["trajectory"]) >= state["info"]["num_steps"]

    @vf.stop
    async def no_tools_called(self, state: State) -> bool:
        """Disable tool stop condition since SciCode is conversation-based, not tool-based."""
        return False

    async def setup_state(self, state: State, **kwargs) -> State:
        """Setup sandbox, initialize step tracking and build prompt."""
        state = await super().setup_state(state, **kwargs)

        state["info"] = dict(state["info"])  # shallow copy to avoid mutation across rollouts
        info = state["info"]
        steps = info["steps"]
        num_steps = len(steps)

        # find the first non-skipped step
        first_step = 0
        while first_step < num_steps and is_skip_step(steps[first_step]["step_number"]):
            first_step += 1

        assert first_step < num_steps

        # initialize step tracking
        state["step"] = first_step
        state["code"] = [None] * num_steps
        state["previous_steps_description"] = ""

        # build previous_steps_description for any skipped initial steps
        for step_idx in range(first_step):
            step = steps[step_idx]
            skip_code = get_skip_step_code(step["step_number"])
            step_description = format_step_description(step, skip_code, info["with_background"])
            state["previous_steps_description"] += step_description
            # Also store in code array so it's available for test execution
            state["code"][step_idx] = skip_code

        # build the prompt for the first non-skipped step
        state["prompt"] = [
            vf.UserMessage(
                content=format_prompt(
                    step=steps[first_step],
                    dependencies=info["dependencies"],
                    with_background=info["with_background"],
                    previous_steps_description=state["previous_steps_description"],
                ),
            )
        ]

        # adjust num_steps to account for skipped initial steps
        info["num_steps"] -= first_step

        return state

    async def env_response(self, messages: Messages, state: State, **kwargs) -> Messages:
        """Generate next user message based on current conversation state and step progress."""

        # update previous steps description
        step = state["info"]["steps"][state["step"]]
        code = state["code"][state["step"]] or ""
        step_description = format_step_description(step, code, state["info"]["with_background"])
        state["previous_steps_description"] += step_description

        # update current step index, handling any skipped steps
        next_step, skipped_steps = state["step"] + 1, 0
        num_steps = len(state["info"]["steps"])
        steps = state["info"]["steps"]
        while next_step < num_steps and is_skip_step(steps[next_step]["step_number"]):
            self.logger.debug(f"Skipping step {steps[next_step]['step_number']}")
            # Add ground truth code for skipped step to previous_steps_description
            skipped_step = state["info"]["steps"][next_step]
            skip_code = get_skip_step_code(skipped_step["step_number"])
            skipped_step_description = format_step_description(
                skipped_step, skip_code, state["info"]["with_background"]
            )
            state["previous_steps_description"] += skipped_step_description
            # Store in code array for test execution
            state["code"][next_step] = skip_code
            next_step += 1
            skipped_steps += 1
        state["step"] = next_step
        state["info"]["num_steps"] -= skipped_steps

        # check if all steps are completed (including skipped ones at the end)
        if next_step >= num_steps:
            return []

        # build fresh prompt for next step (replaces state["prompt"])
        next_prompt = format_prompt(
            step=state["info"]["steps"][next_step],
            dependencies=state["info"]["dependencies"],
            with_background=state["info"]["with_background"],
            previous_steps_description=state["previous_steps_description"],
        )

        self.logger.debug(f"Generated prompt for step {state['info']['steps'][next_step]['step_number']}")

        return [vf.UserMessage(content=next_prompt)]

    async def get_prompt_messages(self, state: State) -> Messages:
        """Return fresh prompt for each step (no conversation history accumulation)."""
        if len(state["trajectory"]) == 0:
            return state["prompt"]
        else:
            next_prompt = await self.env_response([], state)
            return next_prompt

    async def render_completion(self, state: State) -> None:
        """Render final completion as interleaved prompt-completions across all trajectory steps (for display purposes)."""
        completion = []
        for step_idx, step in enumerate(state["trajectory"]):
            if step_idx != 0:
                completion.extend(step["prompt"])
            completion.extend(step["completion"])
        state["completion"] = completion

    async def add_trajectory_step(self, state: State, trajectory_step: vf.TrajectoryStep) -> None:
        """Parse and store generated code from each turn."""
        await super().add_trajectory_step(state, trajectory_step)

        # parse code from this turn's completion
        completion = trajectory_step.get("completion", [])
        code = self.parser.parse_answer(completion)

        # store in state at current step index
        current_step = state["step"]
        assert current_step < len(state["code"])
        state["code"][current_step] = code

        self.logger.debug(f"Parsed code for step {state['info']['steps'][current_step]['step_number']}")

    async def post_rollout(self, state: State) -> None:
        """Run all step tests in sandbox before deletion."""

        self.logger.debug(f"Starting to run tests for problem {state['info']['problem_id']}")
        test_start_time = time.perf_counter()

        info = state.get("info", {})
        sandbox_id = state.get("sandbox_id")
        sandbox_state = state.get("sandbox_state")

        # guard against post_rollout being called when setup_state failed
        if not sandbox_id or "code" not in state:
            return

        running_chunks: list[str] = []
        test_results: list[dict] = []

        for step_idx, (step, code) in enumerate(zip(info["steps"], state["code"])):
            is_step_skipped = is_skip_step(step["step_number"])

            # skip testing for skipped steps, but still accumulate code below
            if is_step_skipped:
                pass
            elif not code:
                self.logger.warning(f"No code generated for step {step['step_number']}")
                test_results.append({"step": step["step_number"], "passed": False})
            else:
                # run test in sandbox
                self.logger.debug(f"Running tests for step {step['step_number']}")
                step_test_start_time = time.perf_counter()
                passed = await self._run_step_test(
                    sandbox_id=sandbox_id,
                    sandbox_state=sandbox_state,
                    code=code,
                    tests=step["test_cases"],
                    step_number=step["step_number"],
                    deps_prelude=info["dependencies"],
                    prefix_code="\n\n".join(running_chunks).strip(),
                )
                step_test_time = time.perf_counter() - step_test_start_time
                self.logger.debug(
                    f"Ran tests for step {step['step_number']} in {print_time(step_test_time)} ({'✓' if passed else '✗'})"
                )
                test_results.append({"step": step["step_number"], "passed": passed})

            # accumulate code for next step context (even for skipped steps, since later code may call these functions)
            if code:
                header = step["function_header"]
                if header:
                    fn = extract_function_name(header)
                    extracted = get_function_from_code(code, fn) if fn else None
                    running_chunks.append(extracted or code)
                else:
                    running_chunks.append(code)

        # store results for reward calculation
        total = len(test_results) or 1
        passed = sum(1 for r in test_results if r["passed"])
        state["test_results"] = test_results
        state["pass_rate"] = passed / total

        test_time = time.perf_counter() - test_start_time
        state["verification_time"] = test_time
        self.logger.debug(
            f"Ran all tests for problem {info['problem_id']} in {print_time(test_time)} ({passed}/{total} passed)"
        )

        await super().post_rollout(state)

    async def _run_step_test(
        self,
        sandbox_id: str,
        sandbox_state: SandboxState,
        code: str,
        tests: list[str],
        step_number: str,
        deps_prelude: str,
        prefix_code: str,
    ) -> bool:
        """Execute a single step's tests in the sandbox."""

        body: list[str] = []
        if deps_prelude.strip():
            body.append(deps_prelude.strip())
        if prefix_code.strip():
            body.append(prefix_code.strip())
        body.append(code)
        body.append("")

        if tests:
            body.append("from scicode_core.parse.parse import process_hdf5_to_tuple")
            body.append(f"targets = process_hdf5_to_tuple('{step_number}', {len(tests)}, '{self.H5_FILE_PATH}')")
            for i, t in enumerate(tests):
                body.append(f"target = targets[{i}]")
                body.append(t)

        script = "\n".join(body)

        try:
            cmd = f"python - <<'PYSCRIPT'\n{script}\nPYSCRIPT"
            result = await self.bash(
                cmd,
                sandbox_id=sandbox_id,
                sandbox_state=sandbox_state,
            )
            return "Error:" not in result and "Traceback" not in result
        except Exception as e:
            self.logger.warning(f"Test for step {step_number} in sandbox {sandbox_id} marked as failed ({e})")
            return False


def load_environment(
    with_background: bool = True,
    timeout_per_test: int = 300,  # seconds
    system_message: str | None = None,
    **kwargs: Any,
) -> vf.Environment:
    eval_dataset = build_dataset(with_background)
    return SciCodeEnv(eval_dataset=eval_dataset, timeout_per_test=timeout_per_test, system_message=system_message)
